name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download LocalXpose
      run: Invoke-WebRequest -Uri "https://github.com/localxpose/localxpose/releases/latest/download/lx-windows-amd64.exe" -OutFile lx.exe

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Start LocalXpose tunnel on port 3389
      run: .\lx.exe tcp 3389 --token $Env:LX_TOKEN
      env:
        LX_TOKEN: ${{ secrets.LX_TOKEN }}
