name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt update && sudo apt install unzip -y

    - name: Download LocalXpose
      run: |
        wget -O lx Run wget -O lx https://api.localxpose.io/api/downloads/loclx-linux-amd64.deb
        chmod +x lx

    - name: Start LocalXpose tunnel on port 3389
      run: ./lx tcp 3389 --token $LX_TOKEN
      env:
        LX_TOKEN: ${{ secrets.LX_TOKEN }}
